      - name: Deploy over SSH 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 22
            nvm use 22
            node -v
            cd ~/AI-Powered-Integrated-Code-Analyzer-for-Efficient-Developer-WorkFlow
            if [ ! -d .git ]; then
                echo "Error: Not a git repository. Exiting."
                exit 1
            fi
            git pull origin main
            cd docai
            npm install
            npm run build
            pm2 restart nextjs-app
