name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20
            nvm use 20
            node -v
            cd ~/AI-Powered-Integrated-Code-Analyzer-for-Efficient-Developer-WorkFlow
            if [ ! -d .git ]; then
                echo "Error: Not a git repository. Exiting."
                exit 1
            fi
            git pull origin main
            cd docai
            
            npm install   
            npm run build 

            # Start or restart app with PM2
            if pm2 describe nextjs-app > /dev/null; then
              echo "PM2 process exists, restarting..."
              pm2 restart nextjs-app
            else
              echo "PM2 process not found, starting a new one..."
              pm2 start npm --name "nextjs-app" -- run start
            fi
            pm2 save