name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            cd ~/AI-Powered-Integrated-Code-Analyzer-for-Efficient-Developer-WorkFlowW
            git pull origin main
            cd docai
            npm install
            npm run build
            pm2 restart nextjs-app
